### ISSUE TITLE
Migrate repo to organization

### ISSUE THREAD

**Issue by vlopezj** [vlopezj/coq-course#13]
We should migrate the repo to an organization, so that it does not depend on my Github account.

**Comment by dschoepe** [comment]
Turns out that even if the owner has free private repos, an organization with private repositories would still not be free. This means we can either skip using an organization or move only the public repository to an organization. I'm not sure what's best here. Given that it's probably a one-time course, I think using an organization in the first place doesn't provide much benefit.

**Comment by AndreasLoow** [comment]
I agree with this, I don't see the point of an organization either.
